/**
 * Daily Reporter V3 — PMWeb Constants
 *
 * These are the EXACT PMWeb dropdown values required for compatibility.
 * Do NOT modify these values without verifying against the live PMWeb system.
 */

// ============================================
// SKY CONDITIONS (multi-select options)
// ============================================
export const SKY_CONDITIONS = [
  { id: 'clear', label: 'Clear', emoji: '☀️' },
  { id: 'partly-cloudy', label: 'Partly Cloudy', emoji: '⛅' },
  { id: 'overcast', label: 'Overcast', emoji: '☁️' },
  { id: 'rain', label: 'Rain', emoji: '🌧️' },
  { id: 'drizzle', label: 'Drizzle', emoji: '🌦️' },
  { id: 'fog', label: 'Fog', emoji: '🌫️' },
  { id: 'windy', label: 'Windy', emoji: '💨' },
  { id: 'hot', label: 'Hot', emoji: '🔥' },
  { id: 'cold', label: 'Cold', emoji: '❄️' },
];

// ============================================
// MANPOWER TRADES (PMWeb LL-codes)
// ============================================
export const DEFAULT_MANPOWER: string[] = [
  "LL-01- Superintendent",
  "LL-02- Foreman",
  "LL-03- Laborers",
  "LL-04- Operator",
  "LL-05- Journeyman",
  "LL-06- Apprentice",
  "LL-07- Engineer",
  "LL-08- PM",
  "LL-09- PE",
  "LL-10- GF",
  "LL-11- Teamster",
  "LL-12- Carpenter",
  "LL-13- Ironworker",
  "LL-14- Pump Operator",
  "LL-15- Cement Mason",
  "LL-16- Vac Truck Operator",
  "LL-17- Electrician",
  "LL-18- Visitor",
  "LL-19- Welder",
  "LL-20- Certified Welding Inspector (CWI)",
  "LL-21- NDT Technician",
  "LL-22- Safety Manager",
  "LL-23- Paleontologist",
  "LL-24- Archaeologist",
  "LL-25- Environmental Monitor",
  "LL-26- Biologist",
  "LL-27- Native American Monitor",
  "LL-28- Pipe Fitter",
  "LL-29- Painters",
  "LL-30- Material Handler",
  "LL-31- Survey Crew",
  "LL-32- AEC NETA Technician",
  "LL-33- RESA Power Technician",
  "LL-34- Plumber",
  "LL-35- ABB - Field Engineer",
  "LL-36- ACE Crane Technician",
  "LL-37- CSI Technician",
  "LL-38- Select Electric Technician",
  "LL-39- Big Sky Electric Tech.",
];

// ============================================
// EQUIPMENT CODES (PMWeb LE-codes)
// ============================================
export const DEFAULT_EQUIPMENT: string[] = [
  "LE-01- Crew Truck",
  "LE-02- CAT 950 Wheel Loader",
  "LE-03- Bobcat",
  "LE-04- Mini Excavator",
  "LE-05- CAT 330 Excavator",
  "LE-07- Skyjacker (fork lift)",
  "LE-09- Skip Loader",
  "LE-10- CAT 336",
  "LE-100- Liebherr LB20 Drill Rig",
  "LE-101- Lily Corp CD15 Epoxy Injection Dispenser",
  "LE-102- AHEARN Single Man Lift",
  "LE-103- Magnum X7 True Airless Epoxy Injection Sprayer",
  "LE-104- McElroy 824 Fusion Welding Machine",
  "LE-105- Generac Generator - United Rentals",
  "LE-106- Link Belt RTC 8075",
  "LE-107- APE Hammer VS200 w/power unit",
  "LE-108- Backhoe",
  "LE-109- Excavator",
  "LE-11- CAT D5 Dozer",
  "LE-110- Compressor",
  "LE-111- Trailer Mounted Blower",
  "LE-112- Hilti PS 1000 Ground Penetrating Radar",
  "LE-113- McElroy Tracstar 16-inch Fusion Machine",
  "LE-114- Crane",
  "LE-115- ABI Mobilram",
  "LE-116- McElroy Tracstar 24-inch Fusion",
  "LE-117- Seal Boss PA 3000 Epoxy Injection Pump",
  "LE-118- Barge",
  "LE-119- John Deere 710K Backhoe Loader",
  "LE-12- CAT 637D Scrapper",
  "LE-120- CAT TL1055 Telehandler",
  "LE-121- Case CX225SR Excavator",
  "LE-122- John Deere 324G Skid Steer",
  "LE-123- John Deere 410L Backhoe",
  "LE-124- CAT D5G LGP Dozer",
  "LE-125- Skid Steer",
  "LE-126- Baker Tank",
  "LE-127- CAT 246D Skid Steer",
  "LE-128- General – Fork Lift",
  "LE-129- Genie Z-30/20N RJ Boom Lift",
  "LE-13- Roller H222",
  "LE-130- Tunnel Boring Machine",
  "LE-131- CAT TRS3312 fork lift",
  "LE-132- Yale 26637 fork lift",
  "LE-133- Snorkel MB26J Man Lift",
  "LE-134- CAT 352 Excavator",
  "LE-135- John Deere 325G Skid Steer",
  "LE-136- John Deere Mini Excavator 35G",
  "LE-139- CAT 410J Loader Backhoe",
  "LE-14- Water Truck F750",
  "LE-140- Ditch Witch HX30 Vacuum Excavator",
  "LE-141- JLG Telehandler 534D10-45",
  "LE-142- HITACHI ZAXIS 75US excavator",
  "LE-143- Cat® 259B Series 3 Compact Track Loader",
  "LE-144- KOBELCO SK210LC Excavator",
  "LE-146- JCB 512 Telehandler",
  "LE-147- Caterpillar 249D3 Compact Track Loader",
  "LE-148- Model No. U55-4 Kubota Tight Tail Swing Compact Excavator",
  "LE-149- BOMAG BW 124 PDH Single Drum Roller",
  "LE-15- Deer 350G excavator",
  "LE-150- Tunnel Slurry Separation Plant",
  "LE-151- KOBELCO SK55SRX-7 Mini Excavator",
  "LE-152- CAT 308E2 CR Mini Excavator",
  "LE-153- Hydraulic Power Unit",
  "LE-154- Bentonite Mixing Tank",
  "LE-155- Wacker Neuson RTLx-SC3 Trench Roller",
  "LE-156- LORAIN LRT-275 Crane",
  "LE-157- Tack Truck",
  "LE-158- CCTV Truck",
  "LE-159- Roller",
  "LE-160- Pup Roller",
  "LE-16- CAT 14H Grader",
  "LE-17- Volvo SD 115 B Compactor",
  "LE-18- CAT D6 Dozer",
  "LE-19- Street sweeper",
  "LE-21- Kobelco SK 485 Excavator",
  "LE-22- Yanmar ViO 25 Mini Excavator",
  "LE-23- Super 10 End Dump Truck",
  "LE-24- Cat 374 FL Excavator",
  "LE-25- Cat D5K2 XL Dozer",
  "LE-26- Cat 966H Loader",
  "LE-27- JLG Lift",
  "LE-28- Water Truck",
  "LE-29- Hamm Single Drum Sheeps Foot Roller",
  "LE-30- Deere 210L Skip Loader",
  "LE-31- Cat 335F Excavator",
  "LE-32- Skytrak Forklift",
  "LE-33- Cat 730C Articulated Haul Truck",
  "LE-34- Concrete Boom Pump",
  "LE-35- Light Tower",
  "LE-36- Sunstate Rental Dump Truck",
  "LE-37- Cat 420F Backhoe",
  "LE-38- Cat 430 Backhoe",
  "LE-39- Cat 304E Mini Ex",
  "LE-40- Badger Vac Truck",
  "LE-41- Saw Cutter",
  "LE-42- Utility Truck",
  "LE-43- Cat 325F Excavator",
  "LE-44- Kobelco CK 1100 Crawler Crane",
  "LE-45- Cat 259D Skid Steer",
  "LE-46- Greenle 555 Pipe Bender",
  "LE-47- Pipe Threader Ridgid 1224",
  "LE-49- PVC Pipe Heater",
  "LE-50- Roto Hammer",
  "LE-51- Pickup Truck",
  "LE-52- CAT 140M2 Grader",
  "LE-53- Cat 315F Excavator",
  "LE-54- Vibratory Soil Compactor CS44B",
  "LE-56- Xtreme Telehandler XR4030",
  "LE-57- Miller Trailblazer Welding Generator",
  "LE-58- Welding Truck",
  "LE-59- Genie S-65 Boom Lift",
  "LE-60- Sakai SV410 Sheepsfoot Roller",
  "LE-61- Wacker RD12 Roller",
  "LE-62- Genie GTH 5519 Forklift",
  "LE-63- Asphalt Paver",
  "LE-64- Truck-Mounted Auger Drill",
  "LE-65- Crane-Mounted Auger Drill",
  "LE-66- Concrete Mixer",
  "LE-67- Concrete Pump Truck",
  "LE-69- Jackhammer",
  "LE-70- Generator",
  "LE-71- Pavement Grinder",
  "LE-72- Arrow Board",
  "LE-75- Polaris Ranger",
  "LE-76- Generator Multiquip",
  "LE-77- Cat 321D LCR Hydraulic Excavator",
  "LE-78- Freightliner M2-106 LW2000",
  "LE-79- Bomag BMP 8500",
  "LE-80- Hamm HD12 Vibratory Roller Compactor",
  "LE-81- Mechanical Wacker",
  "LE-82- Vactor Truck",
  "LE-83- Equipment-Hauling Trailer",
  "LE-84- TracStar 900 HDPE Fusion Machine",
  "LE-85- Maxim 250 Crawler Crane",
  "LE-86- CAT TL1255D",
  "LE-87- Kenworth - T370",
  "LE-89- McElroy 2401 Fusion Welding Machine",
  "LE-90- MQ Power 70 Whisperwatt Generator",
  "LE-91- Model – BOMAG 211D Roller",
  "LE-92- McElroy 711301",
  "LE-93- Maxim LR 1100 Crane",
  "LE-94- Lincoln LN-25 Wire Feeder",
  "LE-95- Lincoln Vantage Welding Generator",
  "LE-96- Toyota Forklift (Mid Capacity 8FGU30)",
  "LE-97- Hoist P550 Forklift",
  "LE-98- Scissor Lift",
  "LE-99- JLG E300AJP Electric Boom Lift",
];

// ============================================
// WORK TYPES
// ============================================
export const WORK_TYPES = [
  'Contract',
  'Extra Work',
  'Force Account',
] as const;

// ============================================
// PAY TYPES (PMWeb)
// ============================================
export const PAY_TYPES = [
  'CS - Cost',
  'EW - Extra Work',
] as const;

// ============================================
// CLASSIFICATIONS (PMWeb)
// ============================================
export const CLASSIFICATIONS = [
  'LR - Labor Regular Time',
  'LO - Labor Overtime',
] as const;

// ============================================
// COMPANY ALIASES
// ============================================
export const COMPANY_ALIASES: Record<string, string> = {
  'OHLA': 'OHL NA',
  'ohla': 'OHL NA',
  'Ohla': 'OHL NA',
};

export const DEFAULT_COMPANY = 'OHL NA';
